name: 'Install Python Dependencies'
description: 'Installs all dependencies'

runs:
  using: composite
  steps:
    - name: Checkout python-greetings repository
      uses: actions/checkout@v6
      with:
        repository: mtararujs/python-greetings
        path: python-greetings
        clean: false

    - name: Create Python virtual environment
      shell: bash
      working-directory: python-greetings
      run: python3 -m venv venv

    - name: Install required pip dependencies
      shell: bash
      working-directory: python-greetings
      run: ./venv/bin/python -m pip install -r requirements.txt
