name: 'Deploy Python Greetings Service'
description: 'Deploys the python-greetings service to an environment'

inputs:
  environment:
    description: 'Environment where to deploy sample app'
    required: true
  port:
    description: 'Port of the deployed service'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout pipeline repository
      uses: actions/checkout@v4

    - name: Checkout python-greetings repository
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: python-greetings

    - name: Stop existing service instance
      shell: bash
      working-directory: python-greetings
      run: pm2 delete greetings-${{ inputs.environment }} || true

    - name: Start service with pm2
      shell: bash
      working-directory: python-greetings
      run: pm2 start app.py --name greetings-${{ inputs.environment }} -- --port ${{ inputs.port }}

